# Generated by Django 3.1.5 on 2021-02-27 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('categoryname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_count', models.IntegerField()),
                ('img_file', models.ImageField(null=True, upload_to='images/cat/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('cname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('img_file', models.ImageField(null=True, upload_to='images/course/', verbose_name='')),
                ('user_count', models.IntegerField()),
                ('categoryname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.categories')),
            ],
        ),
        migrations.CreateModel(
            name='enrollDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='in progress', max_length=100)),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.courses')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.userdetails', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='coursevideocontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='')),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.courses')),
            ],
        ),
        migrations.CreateModel(
            name='coursecontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_file', models.FileField(upload_to='files/', verbose_name='')),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.courses')),
            ],
        ),
    ]
